language: julia
julia:
  - nightly
  - 1.0
  - 1.1
  - 1.2
  - 1.3
env:
  - PYTHON=""
services:
  - xvfb
matrix:
  allow_failures:
    - julia: nightly
addons:
  apt:
    update: true
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
