name = "MinAtar"
uuid = "a0b457aa-173f-450d-9d76-dd2c7c1da9bd"
authors = ["Matthew Schlegel <mkschleg@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
